functionsDirectory = "/data/data/com.termux/files/home/mulakhis/netlify/functions"
functionsDirectoryOrigin = "config"
plugins = []
headers = []
redirects = []

[build]
publish = "/data/data/com.termux/files/home/mulakhis/public"
publishOrigin = "config"
functions = "/data/data/com.termux/files/home/mulakhis/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]